- name: create a user using a variable
  hosts: all
  become: true
  vars:
    user: lisa
    ansible_ssh_private_key_file: "/home/ec2-user/xxxxxxxxxxxxx.pem"
  tasks:
    - name: create a user {{ user }}
      user:
        name: "{{ user }}"