# Basic provisioning example
- name: Ansible test
hosts: localhost
tasks:
- name: launching AWS instance using Ansible
ec2:
key_name: win-key
instance_type: t2.micro
image: ami-05fa00d4c63e32376
region: us-east-1
wait: yes
group: Ansible
count: 1
vpc_subnet_id: default
assign_public_ip: yes
#aws_access_key: ***********xxxxxxxx
#Aws_secret_key: ***********xxxxxxxx